### ISSUE TITLE
Dokumentation - Enas om Milestones

### ISSUE THREAD

**Issue by theuggla** [1dv611-futurum-project/futurum-project#55]
- [x] Skriv milestones i wikin
- [x] Få feedback från grupp
- [x] Uppdatera i wikin
- [x] Överför till Asana
- [x] Lägg in projektplanen
